/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class CreateOneTimeTokenRequest : IEquatable<CreateOneTimeTokenRequest>
    {
        /// <summary>
        /// Gets or Sets StreamingId
        /// </summary>
        [DataMember(Name="streamingId", EmitDefaultValue=false)]
        public string StreamingId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateOneTimeTokenRequest {\n");
            sb.Append("  StreamingId: ").Append(StreamingId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateOneTimeTokenRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateOneTimeTokenRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateOneTimeTokenRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateOneTimeTokenRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    StreamingId == other.StreamingId ||
                    StreamingId != null &&
                    StreamingId.Equals(other.StreamingId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (StreamingId != null)
                    hashCode = hashCode * 59 + StreamingId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateOneTimeTokenRequest left, CreateOneTimeTokenRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateOneTimeTokenRequest left, CreateOneTimeTokenRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
