/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class Tool : IEquatable<Tool>
    {
        /// <summary>
        /// Gets or Sets ToolId
        /// </summary>
        [DataMember(Name="toolId", EmitDefaultValue=false)]
        public string ToolId { get; set; }

        /// <summary>
        /// Gets or Sets ToolName
        /// </summary>
        [DataMember(Name="toolName", EmitDefaultValue=false)]
        public string ToolName { get; set; }

        /// <summary>
        /// Analysis or drawing
        /// </summary>
        /// <value>Analysis or drawing</value>
        [DataMember(Name="toolType", EmitDefaultValue=false)]
        public string ToolType { get; set; }

        /// <summary>
        /// Gets or Sets ToolMetadataType
        /// </summary>
        [DataMember(Name="toolMetadataType", EmitDefaultValue=false)]
        public string ToolMetadataType { get; set; }

        /// <summary>
        /// Gets or Sets IsDefaultTool
        /// </summary>
        [DataMember(Name="isDefaultTool", EmitDefaultValue=false)]
        public bool IsDefaultTool { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Tool {\n");
            sb.Append("  ToolId: ").Append(ToolId).Append("\n");
            sb.Append("  ToolName: ").Append(ToolName).Append("\n");
            sb.Append("  ToolType: ").Append(ToolType).Append("\n");
            sb.Append("  ToolMetadataType: ").Append(ToolMetadataType).Append("\n");
            sb.Append("  IsDefaultTool: ").Append(IsDefaultTool).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Tool)obj);
        }

        /// <summary>
        /// Returns true if Tool instances are equal
        /// </summary>
        /// <param name="other">Instance of Tool to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Tool other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ToolId == other.ToolId ||
                    ToolId != null &&
                    ToolId.Equals(other.ToolId)
                ) && 
                (
                    ToolName == other.ToolName ||
                    ToolName != null &&
                    ToolName.Equals(other.ToolName)
                ) && 
                (
                    ToolType == other.ToolType ||
                    ToolType != null &&
                    ToolType.Equals(other.ToolType)
                ) && 
                (
                    ToolMetadataType == other.ToolMetadataType ||
                    ToolMetadataType != null &&
                    ToolMetadataType.Equals(other.ToolMetadataType)
                ) && 
                (
                    IsDefaultTool == other.IsDefaultTool ||
                    
                    IsDefaultTool.Equals(other.IsDefaultTool)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ToolId != null)
                    hashCode = hashCode * 59 + ToolId.GetHashCode();
                    if (ToolName != null)
                    hashCode = hashCode * 59 + ToolName.GetHashCode();
                    if (ToolType != null)
                    hashCode = hashCode * 59 + ToolType.GetHashCode();
                    if (ToolMetadataType != null)
                    hashCode = hashCode * 59 + ToolMetadataType.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsDefaultTool.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Tool left, Tool right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Tool left, Tool right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
