/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UnreviewedTool : IEquatable<UnreviewedTool>
    {
        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public string UserId { get; set; }
        
        /// <summary>
        /// Gets or Sets ToolType
        /// </summary>
        [DataMember(Name="toolType", EmitDefaultValue=false)]
        public string ToolType { get; set; }

        /// <summary>
        /// Gets or Sets ToolId
        /// </summary>
        [DataMember(Name="toolId", EmitDefaultValue=false)]
        public string ToolId { get; set; }

        /// <summary>
        /// Gets or Sets ToolDll
        /// </summary>
        [DataMember(Name="toolDll", EmitDefaultValue=false)]
        public string ToolDll { get; set; }

        /// <summary>
        /// Gets or Sets ToolModel
        /// </summary>
        [DataMember(Name="toolModel", EmitDefaultValue=false)]
        public string ToolModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UnreviewedTool {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ToolId: ").Append(ToolId).Append("\n");
            sb.Append("  ToolDll: ").Append(ToolDll).Append("\n");
            sb.Append("  ToolModel: ").Append(ToolModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UnreviewedTool)obj);
        }

        /// <summary>
        /// Returns true if UnreviewedTool instances are equal
        /// </summary>
        /// <param name="other">Instance of UnreviewedTool to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnreviewedTool other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    UserId == other.UserId ||
                    UserId != null &&
                    UserId.Equals(other.UserId)
                ) && 
                (
                    ToolId == other.ToolId ||
                    ToolId != null &&
                    ToolId.Equals(other.ToolId)
                ) && 
                (
                    ToolDll == other.ToolDll ||
                    ToolDll != null &&
                    ToolDll.Equals(other.ToolDll)
                ) && 
                (
                    ToolModel == other.ToolModel ||
                    ToolModel != null &&
                    ToolModel.Equals(other.ToolModel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (UserId != null)
                    hashCode = hashCode * 59 + UserId.GetHashCode();
                    if (ToolId != null)
                    hashCode = hashCode * 59 + ToolId.GetHashCode();
                    if (ToolDll != null)
                    hashCode = hashCode * 59 + ToolDll.GetHashCode();
                    if (ToolModel != null)
                    hashCode = hashCode * 59 + ToolModel.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UnreviewedTool left, UnreviewedTool right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UnreviewedTool left, UnreviewedTool right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
