/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
using Swashbuckle.Swagger.Annotations;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class MediaStorageApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Endpoint for Store Video use case</remarks>
        /// <param name="file"></param>
        /// <response code="200">Video has been stored</response>
        /// <response code="500">An error occurred in the backend code</response>
        [HttpPost]
        [Route("/media/storeVideo")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        [SwaggerOperation("StoreVideo")]
        [SwaggerResponse(statusCode: 200, type: typeof(StoreVideoResponse), description: "Video has been stored")]
        [SwaggerResponse(statusCode: 500, type: typeof(EmptyObject), description: "An error occurred in the backend code")]
        public abstract IActionResult StoreVideo(IFormFile file);
    }
}
