/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class TestApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Test if the server is online</remarks>
        /// <param name="echoRequest"></param>
        /// <response code="200">Ping successful</response>
        [HttpPost]
        [Route("/test/echo")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(PingResponse))]
        public abstract IActionResult Echo([FromBody]EchoRequest echoRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Test if the server is online</remarks>
        /// <response code="200">Ping successful</response>
        [HttpPost]
        [Route("/test/ping")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(PingResponse))]
        public abstract IActionResult Ping();
    }
}
