/*
 * High Five
 *
 * The OpenAPI specification for High Five's controllers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class UserApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Endpoint for Delete Media use case</remarks>
        /// <response code="200">A user&#39;s media is purged</response>
        [HttpPost]
        [Route("/users/deleteMedia")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(EmptyObject))]
        public abstract IActionResult DeleteMedia();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Endpoint for Get All Users use case</remarks>
        /// <response code="200">All users are returned</response>
        [HttpPost]
        [Route("/users/getAllUsers")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(GetAllUsersResponse))]
        public abstract IActionResult GetAllUsers();
    }
}
