openapi: 3.0.0

info:
  version: 0.0.1
  title: High Five
  description: The OpenAPI specification for High Five's controllers

tags:
  - name: "MediaStorage"

  #==========================================================
  #     PATHS 
  #==========================================================
paths:

  #==========================================================
  #     VIDEO STORAGE SUBSYSTEM PATHING
  #==========================================================

  /media/storeVideo:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Store Video use case
      operationId: StoreVideo
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/videoObject'
      responses:
        "200":
          description: Video has been stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'
        "500":
          description: An error occurred in the backend code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'
        


  #==========================================================
  #     SCHEMAS 
  #==========================================================
components:
  schemas:

    #==========================================================
    #     VIDEO STORAGE COMPONENTS
    #==========================================================

    videoObject:
      type: object
      properties:
        file:
          type: string
          format: binary

    #==========================================================
    #     GENERIC COMPONENTS
    #==========================================================

    emptyObject:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  