openapi: 3.0.0

info:
  version: 0.0.1
  title: High Five
  description: The OpenAPI specification for High Five's controllers

tags:
  - name: "MediaStorage"
  - name: "Test"
  - name: "Pipelines"

  #==========================================================
  #     PATHS
  #==========================================================
paths:

  #==========================================================
  #     TEST SUBSYSTEM PATHING
  #==========================================================

  /test/ping:
    post:
      tags:
        - "Test"
      description: Test if the server is online
      operationId: Ping
      responses:
        "200":
          description: Ping successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'

  /test/echo:
    post:
      tags:
        - "Test"
      description: Test if the server is online
      operationId: Echo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/echoRequest'
      responses:
        "200":
          description: Ping successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'

  #==========================================================
  #     MEDIA STORAGE SUBSYSTEM PATHING
  #==========================================================

  /media/storeVideo:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Store Video use case
      operationId: StoreVideo
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/storeVideoRequest'
      responses:
        "200":
          description: Video has been stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storeVideoResponse'

  /media/getAllVideos:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Get All Videos use case
      operationId: GetAllVideos
      responses:
        "200":
          description: Returns a list of metadata objects of all the videos in the blob storage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllVideosResponse'

  /media/getVideo:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Get Videos use case
      operationId: GetVideo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getVideoRequest'
            example:
              id: 166E8063E69164B056918CFE1CFF6B6E
      responses:
        "200":
          description: Returns a list of the filenames of all videos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getVideoResponse'
        "400":
          description: Invalid video id provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'

  /media/deleteVideo:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Delete Video use case
      operationId: DeleteVideo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteVideoRequest'
      responses:
        "200":
          description: Video successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'

  /media/storeImage:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Store Image use case
      operationId: StoreImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/storeImageRequest'
      responses:
        "200":
          description: Image has been stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/storeImageResponse'

  /media/getAllImages:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Get All Images use case
      operationId: GetAllImages
      responses:
        "200":
          description: Returns a list of images in the blob storage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllImagesResponse'

  /media/deleteImage:
    post:
      tags:
        - "MediaStorage"
      description: Endpoint for Delete Image use case
      operationId: DeleteImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteImageRequest'
      responses:
        "200":
          description: Image successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'
  
  #==========================================================
  #     PIPELINES SUBSYSTEM PATHING
  #==========================================================

  /pipelines/createPipeline:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Create Pipeline use case
      operationId: CreatePipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createPipelineRequest'
      responses:
        "200":
          description: Pipeline has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createPipelineResponse'

  /pipelines/getPipelines:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Get Pipelines use case
      operationId: GetPipelines
      responses:
        "200":
          description: All pipelines have been returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPipelinesResponse'

  /pipelines/addTools:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Add Tools use case
      operationId: AddTools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addToolsRequest'
      responses:
        "200":
          description: Tools have been added to pipeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'

  /pipelines/removeTools:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Remove Tools use case
      operationId: RemoveTools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/removeToolsRequest'
      responses:
        "200":
          description: Tools have been removed from pipeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'

  /pipelines/deletePipeline:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Delete Pipeline use case
      operationId: DeletePipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deletePipelineRequest'
      responses:
        "200":
          description: Tools have been removed from pipeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyObject'

  /pipelines/getAllTools:
    post:
      tags:
        - "Pipelines"
      description: Endpoint for Get All Tools use case
      operationId: GetAllTools
      responses:
        "200":
          description: All existing tools have been returned
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  #==========================================================
  #     SCHEMAS
  #==========================================================
components:
  schemas:

    #==========================================================
    #     TEST COMPONENTS
    #==========================================================

    pingResponse:
      type: object
      properties:
        message:
          type: string

    echoRequest:
      type: object
      properties:
        message:
          type: string

    #==========================================================
    #     MEDIA STORAGE COMPONENTS
    #==========================================================

    storeVideoRequest:
      type: object
      properties:
        file:
          type: string
          format: binary

    storeImageRequest:
      type: object
      properties:
        file:
          type: string
          format: binary

    storeImageResponse:
      type: object
      properties:
        success:
          type: boolean
        imageId:
          type: string

    storeVideoResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    retrieveVideosResponse:
      type: object
      properties:
        fileName:
          type: string

    getAllVideosResponse:
      type: object
      properties:
        videos:
          type: array
          items:
            $ref: '#/components/schemas/videoMetaData'

    getAllImagesResponse:
      type: object
      properties:
        images:
          type: array
          items:
            $ref: '#/components/schemas/getImageResponse'

    getVideoRequest:
      type: object
      properties:
        id:
          type: string
          description: unique id assossciated with a certain video stored on the blob storage

    getVideoResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        dateStored:
          type: string
          format: date-time
          description: The date-time notation as defined by RFC 3339, section 5.6. e.g. 2017-07-21T17:32:28Zring
        file:
          type: string
          format: byte

    getImageResponse:
      type: object
      properties:
        file:
          type: string
          format: byte

    videoMetaData:
      type: object
      properties:
        name:
          type: string
        duration:
          type: integer
          description: duration of the video in seconds
        dateStored:
          type: string
          format: date-time
          description: The date-time notation as defined by RFC 3339, section 5.6. e.g. 2017-07-21T17:32:28Z
        id:
          type: string
        thumbnail:
          type: string
          format: byte

    deleteVideoRequest:
      type: object
      properties:
        id:
          type: string
          description: unique id assossciated with a certain video stored on the blob storage

    deleteImageRequest:
      type: object
      properties:
        id:
          type: string
          description: unique id assossciated with a certain image stored on the blob storage

    #==========================================================
    #     PIPELINES COMPONENTS
    #==========================================================

    createPipelineRequest:
      type: object
      properties:
        pipeline:
          $ref: '#/components/schemas/newPipeline'

    createPipelineResponse:
      type: object
      properties:
        pipelineId:
          type: string

    getPipelinesResponse:
      type: object
      properties:
        pipelines:
          type: array
          items:
            $ref: '#/components/schemas/pipeline'

    newPipeline:
      type: object
      properties:
        name:
          type: string
        tools:
          type: array
          items:
            type: string
            description: All the tools stored as strings

    pipeline:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          description: Unique id associated with the pipeline
        tools:
          type: array
          items:
            type: string
            description: All the tools stored as strings

    addToolsRequest:
      type: object
      properties:
        pipelineId:
          type: string
        tools:
          type: array
          items:
            type: string

    removeToolsRequest:
      type: object
      properties:
        pipelineId:
          type: string
        tools:
          type: array
          items:
            type: string

    deletePipelineRequest:
      type: object
      properties:
        pipelineId:
          type: string

    #==========================================================
    #     GENERIC COMPONENTS
    #==========================================================

    emptyObject:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
