# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: Android Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'
  pull_request:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Make gradlew executable
        working-directory: ./mobile
        run: chmod 777 ./gradlew
        
      - name: Download and install Gradle
        working-directory: ./mobile
        run: |
          sudo apt install -y unzip wget
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-*.zip
          export GRADLE_HOME=/opt/gradle/gradle-7.0.2
          export PATH=${GRADLE_HOME}/bin:${PATH}
          
      - name: Create mock local.properties file
        working-directory: ./mobile
        run: |
          touch local.properites
          echo "CLIENT_ID=stub" >> local.properties
          echo "DISCOVERY_URI=stub" >> local.properties
          echo "TOKEN_URI=stub" >> local.properties
          echo "REDIRECT_URI=stub" >> local.properties
          echo "END_SESSION_REDIRECT_URI=stub" >> local.properties
          echo "AUTHORIZATION_SCOPE=stub" >> local.properties
          echo "HTTPS_REQUIRED=true" >> local.properties
          echo "DJI_SDK_API_KEY=stub" >> local.properties

      # Execute unit tests
      - name: Building Android
        working-directory: ./mobile
        run: gradle build

      - name: Android Build Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
