# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: Android Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'
  pull_request:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        working-directory: ./mobile
        run: chmod 777 ./gradlew
        
      - name: Install Gradle
        working-directory: ./mobile
        run: sudo apt install -y gradle
        
      - name: Create gradle wrapper
        working-directory: ./mobile
        run: gradle wrapper

      # Execute unit tests
      - name: Unit Test
        working-directory: ./mobile
        run: bash gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
