# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: Android Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'
  pull_request:
    branches:
      - 'development'
      - 'master'
      - 'mobile-development'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Make gradlew executable
        working-directory: ./mobile
        run: chmod 777 ./gradlew
        
      - name: Download and install Gradle
        working-directory: ./mobile
        run: |
          sudo apt install -y unzip wget
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip -P /tmp
          sudo unzip -d /opt/gradle /tmp/gradle-*.zip
          export GRADLE_HOME=/opt/gradle/gradle-7.0.2
          export PATH=${GRADLE_HOME}/bin:${PATH}
          touch local.properties
          

      # Execute unit tests
      - name: Unit Test
        working-directory: ./mobile
        run: gradle testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
