name: .NET Core Unit Tests

on:
  push:
    branches:
      - 'development'
      - 'master'
      - 'backend-development'
  pull_request:
    branches:
      - 'development'
      - 'master'
      - 'backend-development'

  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
          
      - name: Build
        working-directory: ./backend/HighFive
        run: dotnet build         
          
      - name: Run dotnet unit tests
        working-directory: ./backend/HighFive
        run: dotnet test --filter Category=UnitTests
          
