# This is a basic workflow to help you get started with Actions

name: Ionic Build

# Controls when the action will run. 
on:
  push:
    branches: 
      - 'development'
      - 'master'
      - 'web-development'
  pull_request:
    branches: 
      - 'development'
      - 'master'
      - 'web-development'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
          
      - name: install @angular/cli
        run: npm install -i -D -E @angular/cli
        
      - name: install ionic
        run: npm install -g @ionic/cli

      - name: install npm dependencies
        working-directory: ./web
        run: npm install

      - name: Build App
        working-directory: ./web
        run: ionic build

 
